### PR TITLE
Openmx

### PR DESCRIPTION
**Pull request by marklhc**
Currently should be fully functioning, but need to add
- [x] Example in documentation
- [x] Unit tests
    - [x] Using Mx gives same estimates as the non-Mx version
    - [x] Using different versions of `mat_ld` and `mat_vc` give same results
    - [x] Coefficients are similar to joint SEM with definition variables.

### CODE REVIEW

**Comment by Gengrui-Zhang** [comment]
@marklhc 
Hi Mark, I reviewed the openmx branch and ran a CMD check and test. Everything seemed perfect. I just wonder if a unit test for `tspa_mx` is needed?

**Comment by marklhc** [comment]
Thanks @Gengrui-Zhang. I did add some unit tests [here](https://github.com/Gengrui-Zhang/R2spa/pull/57/files#diff-bf286eca5df09b496e44660a66448943ec6f5b1440c132f1a4aaeb93589d7918) as part of the pull request. Please let me know if you couldn't find it. Also, could you go through the vignette (if you haven't), and let me know if there are any conceptual or programmatic questions? Any thoughts would help. Thanks.

**Comment by Gengrui-Zhang** [comment]
Hi Mark, 

Thanks for letting me know! I'll review it tonight. 
Yes I reviewed the vignette yesterday. Here is a list of points I have:
- The parameter estimates of path and covariances from using OpenMX framework and `tspa` functions are pretty much the same.
- It seems that mean structure could work in `tspa` now, right? I saw your comments a few days ago. I believe we can discuss how to implement it in our meeting tomorrow, and then I can further review the results.
- Does this command `fs_dem60 + fs_ind60 ~ 1` mean fixing means of `fs_dem60` and `fs_ind60` to 1?
- Just curious, what's the difference between `fscores` in `mirt` and your function `get_fs`? Can we use `get_fs` for the IRT example?
- I found that in the example of using IRT and joint model, the loadings from `f1` to `f2` is 0.314 (raw factor score regression), 0.540 (Lavaan `sem`), 0.492 (`tspa_mx_model`). And you fixed the path to 0.5 in the simulation, right? It makes sense that the raw regression is 0.314 due to the attenuation, but why was the path using WLS estimator inflated? Finally, can I conclude that `tspa` method had the best performance in restoring the true path coefficient?

**Comment by marklhc** [comment]
Thanks @Gengrui-Zhang! These are all helpful points/questions. I'll merge the branch now.

**Pull request merged**
